version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bioflow
      POSTGRES_PASSWORD: bioflow
      POSTGRES_DB: bioflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bioflow -d bioflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - /Users/hieunguyen/src/bioflow-portal/data/uploads:/Users/hieunguyen/src/bioflow-portal/data/uploads
      - /Users/hieunguyen/src/bioflow-portal/data/results:/Users/hieunguyen/src/bioflow-portal/data/results
      - /Users/hieunguyen/src/bioflow-portal/data/explore:/Users/hieunguyen/src/bioflow-portal/data/explore
      - /Users/hieunguyen/src/bioflow-portal/backend/app/r_scripts:/Users/hieunguyen/src/bioflow-portal/backend/app/r_scripts
      - /Users/hieunguyen/src/bioflow-portal/nextflow:/Users/hieunguyen/src/bioflow-portal/nextflow
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    environment:
      HOST_DATA_DIR: /Users/hieunguyen/src/bioflow-portal/data
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  shiny:
    build: ./shiny
    ports:
      - "3838:3838"
    restart: unless-stopped

volumes:
  pgdata:
