#' Calculate Copy Number Alterations (CNA) from Fragment Count Data
#'
#' @description
#' This script calculates copy number alterations (CNA) from fragment count data
#' processed through QDNAseq. It is specifically designed for DELFI data downloaded
#' from FinaleDB. The script takes fragment counts in predefined genomic bins,
#' applies QDNAseq filtering and normalization, and outputs copy number log2-ratios
#' in BED format.
#'
#' @details
#' The workflow consists of the following steps:
#' 1. Read fragment count file (generated by bedtools intersect)
#' 2. Generate QDNAseq read count object with binned fragment data
#' 3. Apply QDNAseq filtering (residual and blacklist)
#' 4. Estimate and correct for technical biases
#' 5. Normalize bins and smooth outliers
#' 6. Segment bins and call copy number gains/losses
#' 7. Format and save results as BED file
#'
#' @usage
#' Rscript calculate_CNA_from_frag.R -i <count_file> -b <bin_file> -o <output_dir>
#'
#' @arguments
#' \describe{
#'   \item{-i, --input}{Character. Path to input count file containing fragment counts
#'     per bin (output from: bedtools intersect -b fragments.bed -a bins.bed -c)}
#'   \item{-b, --bin}{Character. Path to QDNAseq bin file in RDS format
#'     (e.g., bin100kb.rds or bin1M.rds)}
#'   \item{-o, --output}{Character. Directory path where output BED file will be saved}
#' }
#'
#' @output
#' A BED-format file with columns: chromosome, start, end, log2.ratio
#' File naming: <sample_name>.<bin_name>.bed
#'
#' @dependencies
#' QDNAseq, Biobase, dplyr, tidyverse, GenomicRanges, BSgenome.Hsapiens.UCSC.hg19,
#' hash, Rsamtools, parallel, argparse, testit, comprehenr
#'
#' @author
#' Trong Hieu Nguyen
#'
#' @note
#' - Input count file must be pre-generated using: 
#'   bedtools intersect -b /path/to/frag/file -a /path/to/bin/file -c
#' - This script is optimized for DELFI datasets from FinaleDB
#' - Requires reference genome BSgenome.Hsapiens.UCSC.hg19 (hg19 coordinates)
# ***** note *****
# this script is specially applied to DELFI data downloaded from FinaleDB!!!

gc()
rm(list = ls())

library(QDNAseq)
library(Biobase)
library(dplyr)
library(tidyverse)
library(GenomicRanges)
library(BSgenome.Hsapiens.UCSC.hg19)
library(hash)
library(Rsamtools)
library(parallel)
library(GenomicRanges)
library(argparse)
library(testit)
library(comprehenr)
options(scipen = 999)

# ***** input args ***** #
# ***** EXAMPLE input args ***** #
# resource.dir <- "/home/hieunguyen/src/ecd_wgs_and_enriched_features/release/resources/QDNAseq"
# outputdir <- "/home/hieunguyen/src/ecd_wgs_and_enriched_features/release/tmp_output"
# path.to.binfile <- file.path(resource.dir, "bin100kb.rds")
# path.to.binfile <- file.path(resource.dir, "bin1M.rds")
# ***** this file was generated by bedtools intersect -c 
# example cmd:
# bedtools intersect -b /path/to/frag/file -a /path/to/bin/file -c > /path/to/output
# path.to.count.file <- "/home/hieunguyen/Downloads/count.bed"

parser <- ArgumentParser()
parser$add_argument("-i", "--input", action="store",
                    help="path to input count file: count number of fragments falling into each bin")
parser$add_argument("-b", "--bin", action="store",
                    help="path to input bam fiel")
parser$add_argument("-o", "--output", action="store",
                    help="Path to save  output")

args <- parser$parse_args()

path.to.count.file <- args$input
outputdir <- args$output
path.to.binfile <- args$bin

bin.name <- str_replace_all(basename(path.to.binfile), ".rds", "")

message(sprintf("Input input file %s", basename(path.to.count.file)))
message(sprintf("output will be saved to %s", outputdir))
message(sprintf("Using the CNA bin file %s, name %s", path.to.binfile, bin.name))

binfile <- readRDS(path.to.binfile)

# ***** run this once, generate bed file for 1M and 100kb bins. ***** #
# savebed <- binfile@data[, c("chromosome", "start", "end")] %>% data.frame()
# write.table(savebed, str_replace(path.to.binfile, ".rds", ".bed"), 
#             sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)

generate_QDNAseq_readCountObj <- function(path.to.count.file, binfile){
  sample.name <- basename(path.to.count.file)
  countdf <- read.csv(path.to.count.file, sep = "\t", header = FALSE)
  colnames(countdf) <- c("chromosome", "start", "end", "count")
  countdf <- countdf %>% rowwise() %>%
    mutate(bin = sprintf("%s:%s-%s", chromosome, start, end)) %>%
    column_to_rownames("bin") %>% subset(select = -c(start, end, chromosome))
  colnames(countdf) <- c(sample.name)
  
  fd <- new("AnnotatedDataFrame", data = countdf)
  pd <- new("AnnotatedDataFrame", data = data.frame(
    name = sample.name,
    total.reads = sum(countdf$count),
    used.reads = sum(countdf$count),
    expected.variance = nrow(binfile@data)/sum(countdf$count)
  ))
  row.names(pd) <- sample.name
  readCounts <- new("QDNAseqReadCounts",
                    counts = as.matrix(countdf),
                    rowRanges = binfile,
                    phenodata = pd,
                    featuredata = fd,
                    bins = binfile)
  return(readCounts)
}

calculate_CNA <- function(readCounts){
  readCountsFiltered <- applyFilters(readCounts, residual=TRUE, blacklist=TRUE)
  readCountsFiltered <- estimateCorrection(readCountsFiltered)
  copyNumbers <- correctBins(readCountsFiltered)
  copyNumbersNormalized <- normalizeBins(copyNumbers)
  copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
  
  copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="log2")
  copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
  
  copyNumbersCalled <- callBins(copyNumbersSegmented)
  function.output <- list(CNA = copyNumbersCalled, readCounts = readCountsFiltered)
  return(function.output)  
}

format_cna_output <- function(cna.obj){
  # ***** save copy number data frame
  # and format the dataframe as <chr>TAB<start>TAB<end>TAB<Log2-ratio>
  cnadf <- data.frame(cna.obj$CNA@assayData$copynumber) %>%
    rownames_to_column("bin.name")
  colnames(cnadf) <- c("bin.name", "log2.ratio")
  cnadf <- cnadf %>% rowwise() %>%
    mutate(chrom = sprintf("chr%s", str_split(bin.name, ":")[[1]][[1]])) %>%
    mutate(start = str_split(str_split(bin.name, ":")[[1]][[2]], "-")[[1]][[1]] ) %>%
    mutate(end = str_split(str_split(bin.name, ":")[[1]][[2]], "-")[[1]][[2]] )
  
  cnadf <- cnadf[, c("chrom", "start", "end", "log2.ratio")]
  return(cnadf)
}

readCounts <- generate_QDNAseq_readCountObj(path.to.count.file, binfile)
cna.bin <- calculate_CNA(readCounts)
output.cnadf <- format_cna_output(cna.bin)

write.table(output.cnadf, 
            file.path(outputdir, sprintf("%s.%s.bed", filename, bin.name)), 
            sep = "\t", 
            row.names = FALSE, 
            col.names = FALSE)

# EOF