import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from tqdm import tqdm
from itertools import combinations
import warnings
warnings.filterwarnings("ignore")
import argparse

def main():
    """
    Generate fragmentomics features (FLEN, EM, ND) and 2D combined image features from WGS fragment data.
    This function processes a fragment TSV file and extracts the following features:
    1. FLEN (Fragment Length): Distribution of fragment lengths
    2. EM (End Motif): Frequency of 4bp end motifs
    3. ND (Nucleosome Distance): Distribution of nucleosome distances
    4. 2D Image Features: Combined distributions of feature pairs
    The function also calculates Shannon entropy for each feature type.
    Dependencies:
        - numpy: For entropy calculations
        - pandas: For data manipulation and CSV I/O
        - argparse: For command-line argument parsing
        - os: For directory creation and system operations
        - itertools.combinations: For generating feature combinations
    Command-line Arguments:
        --input (str, required): Path to the input TSV file containing DNA fragment data
        --output (str, required): Path to the directory where output files will be saved
        --min_flen (int, required): Minimum fragment length threshold for analysis
        --max_flen (int, required): Maximum fragment length threshold for analysis
    Output Files:
        - {sampleid}_FLEN.csv: Fragment length distribution with columns [size, freq, count]
        - {sampleid}_EM.csv: End motif frequency with columns [motif, freq]
        - {sampleid}_ND.csv: Nucleosome distance distribution with columns [dist, freq]
        - 2D_features/{feature1}_{feature2}.csv: 2D joint distributions for all valid feature pairs
        - FLEN_EM_ND_entropy.csv: Shannon entropy values for FLEN, EM, and ND features
    Returns:
        None. Results are written to output directory.
    Raises:
        FileNotFoundError: If input_tsv file does not exist
        SystemExit: If required arguments are missing
    """
    # ***** helper classes and function ***** #
    class WGS_GW_Image_features:
        '''
        Class WGS_GW_Image_features stores the input .frag.tsv data frame. .frag.tsv dataframe is a fragment-wise
        tab-separated file with the following columns: chromosome, start position, end position, fragment length, read ID, QC score,
        forward nucleosome distance, reverse nucleosome distance, forward end motif, reverse end motif (4bp).
        From the input .frag.tsv data frame, the class generates the following features:
        1. FLEN: fragment length distribution vector 
        2. EM: end motif frequency vector
        3. NUC: nucleosome distance distribution vector
        4. image features generated by combining fragments' FLEN, EM, and NUC features.
    '''
    # ***** basic class definition ***** #
        def __init__(self,
                     input_tsv,
                     min_flen, 
                     max_flen,
                     outputdir):
            self.input_tsv = input_tsv
            self.sampleid = input_tsv.split("/")[-1].replace("_FLEN_EM_ND.tsv", "")
            print("reading in the input frag.tsv data")
            self.min_flen = min_flen
            self.max_flen = max_flen
            self.maindf = pd.read_csv(input_tsv, sep = "\t", header = None)
            self.maindf.columns = ["chr", 
                                    "start", 
                                    "end", 
                                    "readID", 
                                    "flen", 
                                    "forward_NUC", 
                                    "reverse_NUC", 
                                    "forward_EM", 
                                    "reverse_EM"
                                    ]
            # convert all forward and reverse EMs to uppercase
            self.maindf["forward_EM"] = self.maindf["forward_EM"].apply(lambda x: x.upper())
            self.maindf["reverse_EM"] = self.maindf["reverse_EM"].apply(lambda x: x.upper())
            
            self.maindf = self.maindf[self.maindf["forward_EM"].str.contains("N") == False]
            self.maindf = self.maindf[self.maindf["reverse_EM"].str.contains("N") == False]
            self.outputdir = outputdir
            os.system(f"mkdir -p {self.outputdir}")
            
            # generate fulldf, to combine features to generate image features
            fulldf1 = pd.DataFrame(data = self.maindf.flen.values, columns= ["full_FLEN"])
            fulldf1["full_EM"] = self.maindf["forward_EM"].values
            fulldf1["forward_EM"] = self.maindf["forward_EM"].values
            fulldf1["reverse_EM"] = self.maindf["reverse_EM"].values
    
            fulldf1["full_NUC"] = self.maindf["forward_NUC"].values
            fulldf1["forward_NUC"] = self.maindf["forward_NUC"].values
            fulldf1["reverse_NUC"] = self.maindf["reverse_NUC"].values
    
            fulldf2 = pd.DataFrame(data = self.maindf.flen.values, columns= ["full_FLEN"])
            fulldf2["full_EM"] = self.maindf["reverse_EM"].values
            fulldf2["forward_EM"] = self.maindf["forward_EM"].values
            fulldf2["reverse_EM"] = self.maindf["reverse_EM"].values
    
            fulldf2["full_NUC"] = self.maindf["reverse_NUC"].values
            fulldf2["forward_NUC"] = self.maindf["forward_NUC"].values
            fulldf2["reverse_NUC"] = self.maindf["reverse_NUC"].values
    
            self.fulldf = pd.concat([fulldf1, fulldf2], axis = 0)   
            
        # ***** generate FLEN feature ***** #
        def generate_flen_feature(self, 
                                  save_feature = True):
            flendf = self.maindf[["flen"]].copy()
            flendf["flen"] = flendf["flen"].astype(int)
            if not flendf.empty:
                flen_count = flendf["flen"].value_counts().reset_index()
                flen_count.columns = ["size", "count"]
                flen_count["freq"] = flen_count["count"] / flen_count["count"].sum()
                flen_count = flen_count.sort_values("size")
                output_flendf = pd.DataFrame({"size": range(self.min_flen, self.max_flen + 1)})
                output_flendf = output_flendf.merge(flen_count, on="size", how="left").fillna(0)
                output_flendf = output_flendf[["size", "freq", "count"]]
                if save_feature:
                    output_flendf.to_csv(os.path.join(self.outputdir, f"{self.sampleid}_FLEN.csv"), index=False)
                return output_flendf
        
        # ***** generate EM feature ***** #
        def generate_em_feature(self, 
                                save_feature = True):
            emdf1 = self.maindf[["reverse_EM"]].copy() 
            emdf2 = self.maindf[["forward_EM"]].copy()
    
            emdf1.columns = ["motif"]
            emdf2.columns = ["motif"]
            
            emdf = pd.concat([emdf1, emdf2], axis = 0)
            emdf.columns = ["motif"]
            emdf = emdf[emdf["motif"].isna() == False]
            # remove any EMs that contain N, keep end motifs which are A, C, G, T
            emdf = emdf[emdf["motif"].str.contains("N") == False]
            output_emdf = emdf["motif"].value_counts().reset_index()
            if not output_emdf.empty:
                output_emdf.columns = ["motif", "count"]
                output_emdf = output_emdf[~output_emdf["motif"].str.contains("N")]
                output_emdf["freq"] = output_emdf["count"] / output_emdf["count"].sum()
                output_emdf = output_emdf[["motif", "freq"]]
                if save_feature:
                    output_emdf.to_csv(os.path.join(self.outputdir, f"{self.sampleid}_EM.csv"), index=False)
                return output_emdf
    
        # ***** generate nucleosome distance feature ***** #
        def generate_nuc_feature(self, 
                                save_feature = True):
            nucdf1 = pd.DataFrame(data = self.maindf["reverse_NUC"].values,
                         columns = ["feat"])
            nucdf2 = pd.DataFrame(data = self.maindf["forward_NUC"].values,
                         columns = ["feat"])
            nucdf = pd.concat([nucdf1, nucdf2], axis = 0)
            nucdf = nucdf[(nucdf["feat"] >= -300) & (nucdf["feat"] <= 300)]
            count_nucdf = nucdf.reset_index().groupby("feat")["index"].count().reset_index()
            count_nucdf["index"] = count_nucdf["index"].apply(lambda x: x/count_nucdf["index"].sum())
            count_nucdf.columns = ["dist", "freq"]
            
            output_nucdf = pd.DataFrame({"dist": range(-300, 301)})
            output_nucdf = output_nucdf.merge(count_nucdf, on="dist", how="left").fillna(0)
                
            if save_feature:
                output_nucdf.to_csv(os.path.join(self.outputdir, f"{self.sampleid}_ND.csv"), index=False)
            return output_nucdf
    
        # ***** generate all image - combined 2D features ***** #
        def generate_all_image_features(self):
            all_features = self.fulldf.columns
            feature_combinations = list(combinations(all_features, 2))  # Generates combinations without replacement
            range_valuedf = {
                "NUC" : pd.DataFrame(
                        {
                            'NUC': range(-300, 301)
                        }
                    ),
                "EM" : pd.DataFrame(
                        {
                            'EM': [f"{i}{j}{k}{l}" 
                                for i in ["A", "C", "G", "T"] 
                                for j in ["A", "C", "G", "T"] 
                                for k in ["A", "C", "G", "T"] 
                                for l in ["A", "C", "G", "T"]]
                        }
                    ),
                "FLEN" : pd.DataFrame(
                        {
                            'FLEN': range(50, 351)
                        }
                    )
            }
            for i in range(len(feature_combinations)):
                selected_features = list(feature_combinations[i])
                feature1 = selected_features[0]
                feature2 = selected_features[1]
                
                if (feature1.split("_")[1] != feature2.split("_")[1]):
                    tmpdf = self.fulldf[selected_features].copy()
                    if "NUC" in feature1:
                        tmpdf = tmpdf[(tmpdf[feature1] >= -300) & (tmpdf[feature1] <= 300)]
                    if "NUC" in feature2:
                        tmpdf = tmpdf[(tmpdf[feature2] >= -300) & (tmpdf[feature2] <= 300)]
                    
                    countdf = tmpdf.reset_index() \
                                    .groupby(selected_features)["index"] \
                                    .count() \
                                    .reset_index() \
                                    .pivot_table(index=feature1, 
                                                columns=feature2, 
                                                values='index', 
                                                fill_value=0)
    
                    countdf = countdf.reset_index().merge(range_valuedf[feature1.split("_")[1]], 
                                                left_on = feature1, 
                                                right_on = feature1.split("_")[1], 
                                                how = "outer")\
                        .fillna(0) \
                        .drop(feature1, axis = 1)
                    countdf = countdf.rename(columns={feature1.split("_")[1]: feature1}).set_index(feature1)
                    countdf = countdf/countdf.sum().sum()
                    os.system(f"mkdir -p {os.path.join(self.outputdir, '2D_features') } ")
                    countdf.to_csv(os.path.join(self.outputdir, "2D_features", "_".join(selected_features)) + ".csv", index = True)
    # ***** end of helper class and functions ***** #
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', 
                        type = str, 
                        required = True, 
                        help = 'Path to the input BED file containing DNA fragments')
    parser.add_argument('--output', 
                        type = str, 
                        required = True, 
                        help = 'Path to save output')
    parser.add_argument('--min_flen', 
                        type = int, 
                        required = True, 
                        help = 'Minimum fragment length')
    parser.add_argument('--max_flen', 
                        type = int, 
                        required = True, 
                        help = 'Maximum fragment length')

    args = parser.parse_args()
    input_tsv = args.input
    outputdir = args.output
    min_flen = args.min_flen
    max_flen = args.max_flen
    
    os.system(f"mkdir -p {outputdir}")
    
    output_obj = WGS_GW_Image_features(
        input_tsv = input_tsv,
        outputdir = outputdir,
        min_flen = min_flen,
        max_flen = max_flen)
    
    output_obj.generate_flen_feature(save_feature = True)
    output_obj.generate_em_feature(save_feature = True)
    output_obj.generate_nuc_feature(save_feature = True)
    output_obj.generate_all_image_features()
    
    emdf = pd.read_csv(os.path.join(outputdir, f"{output_obj.sampleid}_EM.csv"))
    flendf = pd.read_csv(os.path.join(outputdir, f"{output_obj.sampleid}_FLEN.csv"))
    nucdf = pd.read_csv(os.path.join(outputdir, f"{output_obj.sampleid}_ND.csv"))
    
    # ***** calculate shannon entropy for FLEN, EM and ND ***** #
    em_entropy = -np.sum([i * np.log(i) for i in emdf.freq.values if i != 0])/np.log(256)
    flen_entropy = -np.sum([i * np.log(i) for i in flendf.freq.values if i != 0])/np.log(max_flen - min_flen + 1)
    nuc_entropy = -np.sum([i * np.log(i) for i in nucdf.freq.values if i != 0])/np.log(601)
    
    entropydf = pd.DataFrame.from_dict(
        {
            "FLEN_ENTROPY" : flen_entropy,
            "EM_ENTROPY" : em_entropy,
            "ND_ENTROPY": nuc_entropy
        },
        orient = "index"
    ).T
    entropydf.to_csv(os.path.join(outputdir, "FLEN_EM_ND_entropy.csv"), sep = "\t")

if __name__ == '__main__':
    main()