import os 
import argparse
import pandas as pd 

def main():
    """
    Parse bedtools genomecov output and calculate average coverage per chromosome.
    The input file is expected to be tab-separated with columns:
        - chrom (str): Chromosome identifier
        - coverage (int): Coverage depth
        - bases_at_cov (int): Number of bases at this coverage level
        - chrom_size (int): Total chromosome size
        - fraction (float): Fraction of chromosome at this coverage (not used)
        --input (str): Path to the genomecov text file generated by 
            `bedtools genomecov -ibam`. Required.
        --output (str): Directory path where the resulting .avgGenomeCov.tsv 
            file will be saved. Required. Directory will be created if it 
            does not exist.
        None
    Output:
        Writes a TSV file named "{sampleid}.avgGenomeCov.tsv" to the specified 
        output directory, containing two columns:
            - chrom: Chromosome identifier
            - cov: Average coverage for that chromosome
    Raises:
        FileNotFoundError: If the input file does not exist.
        ValueError: If the input file format is invalid.
    Example:
        python script.py --input genomecov.txt --output ./results/
    """
    # input arg
    # exampel
    # inputfile = "/Users/hieunguyen/storage/WGS_bam/outputdir/input.sorted.genomeCov.txt"
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', 
                        type = str, 
                        required = True, 
                        help = 'Path to the output file generated by bedtools genomecov -ibam')
    parser.add_argument('--output', 
                        type = str, 
                        required = True, 
                        help = 'Path to save output')
    args = parser.parse_args()
    inputfile = args.input
    outputdir = args.output

    os.system(f"mkdir -p {outputdir}")

    sampleid = inputfile.split("/")[-1].split(".")[0]
    
    chrom_count = dict()
    chrom_sizes = dict()
    avg_cov = dict()
    
    genomecov_output = open(inputfile,"r")
    
    for line in genomecov_output.readlines():
        chrom,cov,bases,size,fraction = line.rstrip().split("\t")
        if chrom not in chrom_count.keys():
            chrom_count[chrom] = 0
            chrom_sizes[chrom] = int(size)
        chrom_count[chrom] += int(cov)*int(bases)
    for chrom in chrom_count.keys():
        avg_cov[chrom] = float(chrom_count[chrom]) / float(chrom_sizes[chrom])
        covdf = pd.DataFrame.from_dict(avg_cov, orient = "index").reset_index()
    covdf.columns = ["chrom", "cov"]
    covdf.to_csv(os.path.join(outputdir, f"{sampleid}.avgGenomeCov.tsv"), sep = "\t", index = False, header = False)

if __name__ == '__main__':
    main()