"""
Python equivalent of rmd/preliminary_analysis.Rmd from the Seurat/R pipeline.

The R report works by pickling ggplot objects directly inside the Seurat
object's `@misc` slot at each pipeline step, then re-printing them at render
time. AnnData/.h5ad has no equivalent slot for arbitrary Python objects, but
every QC/ambient-RNA/cell-cycle metric computed upstream is still sitting in
`adata.obs` (obs columns are never dropped by later steps), so this script
simply re-derives every plot straight from the final .h5ad's `obs`/`obsm`
instead of needing plot objects passed forward between steps.

Produces a single self-contained HTML file (plots embedded as base64 PNGs,
tables rendered with DataTables.net via CDN — the same JS library the R
report used through `DT::datatable()` / create_dt()).
"""
import argparse
import os
import sys

import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from helper_functions import create_dt_html, fig_to_base64_img  # noqa: E402

sc.settings.verbosity = 1

HTML_HEAD = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Preliminary analysis — {sample}</title>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
<style>
  body {{ font-family: -apple-system, Helvetica, Arial, sans-serif; margin: 30px; max-width: 1400px; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 6px; }}
  h2 {{ margin-top: 40px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }}
  h3 {{ margin-top: 25px; color: #444; }}
  .grid {{ display: flex; flex-wrap: wrap; gap: 16px; }}
  .grid img {{ max-width: 420px; border: 1px solid #ddd; }}
  table.dataTable {{ font-size: 12px; }}
</style>
</head>
<body>
<h1>Preliminary analysis — {sample}</h1>
<p><em>Generated by single_cell_data_analysis_with_python (scanpy pipeline)</em></p>
"""

TABLEAU20 = [
    "#4E79A7", "#A0CBE8", "#F28E2B", "#FFBE7D", "#59A14F",
    "#8CD17D", "#B6992D", "#F1CE63", "#499894", "#86BCB6",
    "#E15759", "#FF9D9A", "#79706E", "#BAB0AC", "#D37295",
    "#FABFD2", "#B07AA1", "#D4A6C8", "#9D7660", "#D7B5A6",
]


def cluster_colors(n):
    return (TABLEAU20 * (n // len(TABLEAU20) + 1))[:n]


def section(title, body, level=2):
    tag = f"h{level}"
    return f"<{tag}>{title}</{tag}>\n{body}\n"


def scatter_umap(adata, umap_key, color_col, title, categorical=False, ax=None):
    fig, ax = plt.subplots(figsize=(6, 5)) if ax is None else (ax.figure, ax)
    emb = adata.obsm[umap_key]
    if categorical:
        cats = adata.obs[color_col].astype("category").cat.categories
        colors = cluster_colors(len(cats))
        for cat, col in zip(cats, colors):
            sel = (adata.obs[color_col] == cat).to_numpy()
            ax.scatter(emb[sel, 0], emb[sel, 1], s=4, c=col, label=str(cat))
        ax.legend(markerscale=3, fontsize=7, loc="best", ncol=2)
    else:
        sca = ax.scatter(emb[:, 0], emb[:, 1], s=4, c=adata.obs[color_col], cmap="viridis")
        fig.colorbar(sca, ax=ax)
    ax.set_title(title)
    ax.set_xlabel("UMAP1"); ax.set_ylabel("UMAP2")
    return fig


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--h5ad", type=str, required=True)
    p.add_argument("--sample", type=str, default="sample")
    p.add_argument("--outdir", type=str, default=".")
    p.add_argument("--cluster_resolution", type=str, default="0.5")
    opt = p.parse_args()

    os.makedirs(opt.outdir, exist_ok=True)
    adata = sc.read_h5ad(opt.h5ad)

    html = [HTML_HEAD.format(sample=opt.sample)]

    # ── Preprocessing and QC ─────────────────────────────────────────────────
    qc_body = ""
    qc_cols = [c for c in ["n_genes_by_counts", "total_counts", "percent_mt", "percent_ribo"]
               if c in adata.obs.columns]
    fig, axes = plt.subplots(1, len(qc_cols), figsize=(4 * len(qc_cols), 4))
    axes = np.atleast_1d(axes)
    for ax, col in zip(axes, qc_cols):
        ax.violinplot(adata.obs[col].dropna(), showmedians=True)
        ax.set_title(col)
    fig.tight_layout()
    qc_body += fig_to_base64_img(fig); plt.close(fig)
    html.append(section("Preprocessing and QC", section("Raw data quality control", qc_body, level=3)))

    # ── Ambient RNA ──────────────────────────────────────────────────────────
    if "AmbientRNA" in adata.obs.columns:
        body = ""
        fig, ax = plt.subplots(figsize=(7, 5))
        adata.obs.boxplot(column="AmbientRNA", by="name", ax=ax)
        ax.set_title("Contamination level in each sample"); ax.set_xlabel(""); plt.suptitle("")
        body += fig_to_base64_img(fig); plt.close(fig)

        if "decontX_clusters" in adata.obs.columns:
            fig, ax = plt.subplots(figsize=(7, 5))
            adata.obs["decontX_clusters"].value_counts().sort_index().plot(kind="bar", ax=ax)
            ax.set_title("Cells per decontX cluster")
            body += fig_to_base64_img(fig); plt.close(fig)

        html.append(section("Ambient RNA background correction (decontX)", body))

    # ── Descriptive statistics + filtering thresholds ───────────────────────
    body = ""
    for col in qc_cols + (["log10GenesPerUMI"] if "log10GenesPerUMI" in adata.obs.columns else []):
        fig, ax = plt.subplots(figsize=(6, 4))
        adata.obs.boxplot(column=col, by="name", ax=ax)
        ax.set_title(f"Distribution of {col} in each dataset"); plt.suptitle("")
        body += fig_to_base64_img(fig); plt.close(fig)
    html.append(section("Descriptive statistics and filtering thresholds", body))

    # ── Descriptive statistics + UMAP ───────────────────────────────────────
    umap_key = "RNA_UMAP" if "RNA_UMAP" in adata.obsm else (
        "X_umap" if "X_umap" in adata.obsm else None)
    if umap_key is not None:
        body = '<div class="grid">'
        for col in ["percent_mt", "percent_ribo", "total_counts", "n_genes_by_counts"]:
            if col not in adata.obs.columns:
                continue
            fig = scatter_umap(adata, umap_key, col, col)
            body += fig_to_base64_img(fig); plt.close(fig)
        body += "</div>"
        html.append(section("Descriptive statistics on UMAP", body))

        # ── Cell cycle scoring ───────────────────────────────────────────────
        if "phase" in adata.obs.columns:
            body = '<div class="grid">'
            fig = scatter_umap(adata, umap_key, "phase", "Cell cycle phase", categorical=True)
            body += fig_to_base64_img(fig); plt.close(fig)
            body += "</div>"
            html.append(section("Cell cycle scoring", body))

    # ── Cluster marker genes ─────────────────────────────────────────────────
    cluster_cols = [c for c in adata.obs.columns if f".cluster.{opt.cluster_resolution}" in c]
    cluster_col = None
    if cluster_cols:
        cluster_col = ("RNA_PCA.cluster." + opt.cluster_resolution
                       if f"RNA_PCA.cluster.{opt.cluster_resolution}" in cluster_cols
                       else cluster_cols[0])

    if cluster_col is not None:
        sc.tl.rank_genes_groups(adata, groupby=cluster_col, method="wilcoxon")
        markers = sc.get.rank_genes_groups_df(adata, group=None)
        markers = markers.rename(columns={"names": "gene", "group": "cluster"})
        markers = markers[(markers["pvals_adj"] < 0.05) & (markers["logfoldchanges"] > 0)]
        markers = markers.sort_values(["cluster", "logfoldchanges"], ascending=[True, False])

        body = ""
        n_clusters = adata.obs[cluster_col].nunique()
        if umap_key is not None:
            for cl in sorted(markers["cluster"].unique(), key=lambda x: (len(x), x)):
                top_genes = markers.loc[markers["cluster"] == cl, "gene"].head(9).tolist()
                if not top_genes:
                    continue
                fig, axes = plt.subplots(3, 3, figsize=(12, 12))
                for ax, gene in zip(axes.flat, top_genes):
                    expr = adata[:, gene].X
                    expr = expr.toarray().flatten() if hasattr(expr, "toarray") else np.asarray(expr).flatten()
                    sca = ax.scatter(adata.obsm[umap_key][:, 0], adata.obsm[umap_key][:, 1],
                                      c=expr, s=3, cmap="viridis")
                    ax.set_title(gene, fontsize=9)
                    ax.set_xticks([]); ax.set_yticks([])
                for ax in axes.flat[len(top_genes):]:
                    ax.axis("off")
                fig.suptitle(f"Cluster {cl} — top marker genes")
                fig.tight_layout()
                body += f"<h4>Cluster {cl}</h4>" + fig_to_base64_img(fig)
                plt.close(fig)
        html.append(section("Cluster marker genes — feature plots", body))

        body = create_dt_html(markers, table_id="markers_table")
        html.append(section("Full table of DE genes", body))

        # ── Cell counts per cluster per sample ──────────────────────────────
        counts = pd.crosstab(adata.obs["name"], adata.obs[cluster_col])
        html.append(section("Number of cells in each cluster in each sample",
                             create_dt_html(counts.reset_index(), table_id="counts_table")))
    else:
        html.append(section("Cluster marker genes",
                             "<p><em>No clustering column found (expected an obs column named "
                             "'&lt;reduction&gt;.cluster.&lt;resolution&gt;' from step 8).</em></p>"))

    html.append("</body></html>")

    out_path = os.path.join(opt.outdir, f"{opt.sample}_preliminary_analysis.html")
    with open(out_path, "w") as f:
        f.write("\n".join(html))
    print(f"Report written to {out_path}")


if __name__ == "__main__":
    main()
